rosrun srs_object_database clientTest oven.txt
rosrun srs_object_database clientTest sink.txt
rosrun srs_object_database clientTest stove.txt
rosrun srs_object_database clientTest fridge.txt
rosrun srs_object_database clientTest sofa.txt
rosrun srs_object_database clientTest dishwasher.txt
rosrun srs_object_database clientTest table.txt
rosrun srs_object_database clientTest kitchentop.txt
rosrun srs_object_database clientTest milkbox.txt
rosrun srs_object_database clientTest pringles.txt
rosrun srs_object_database clientTest salt.txt
rosrun srs_object_database clientTest bottle.txt
